// ChatGPT/flask_apps/app18/frontend/src/App.svelte
<script>
  let message = 'Loading...';

  async function fetchMessage() {
    try {
      const response = await fetch('http://localhost:5035/');
      const data = await response.json();
      message = data.message;
    } catch (error) {
      message = 'Error connecting to ChatGPT backend';
    }
  }

  fetchMessage();
</script>

<main>
  <h1>ChatGPT App</h1>
  <p class="message">{message}</p>
</main>

<style>
  main {
    text-align: center;
    padding: 2em;
  }
  h1 {
    color: #333;
    font-size: 2em;
    margin-bottom: 0.5em;
  }
  .message {
    color: #444;
    font-size: 1.2em;
    margin: 1em;
  }
</style>

// models/agentica-org_deepcoder-14b-preview/app6/frontend/src/App.jsx
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom/client';

const App = () => {
  const [message, setMessage] = useState('Loading...');

  useEffect(() => {
    // Fetch the message from the backend server running on port 6451
    fetch('http://localhost:6451')
      .then((response) => {
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        return response.json();
      })
      .then((data) => {
        setMessage(data.message || 'No message received');
      })
      .catch((error) => {
        setMessage(`Error fetching message: ${error.message}`);
      });
  }, []);

  return (
    <main>
      <h1>{message}</h1>
    </main>
  );
};

const container = document.getElementById('root');
if (container) {
  const root = ReactDOM.createRoot(container);
  root.render(<App />);
}

export default App;
